config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :contacts, :conferences
  
  get '/login', to: 'sessions#new', as: :login_form_path
  delete '/sessions', to: 'sessions#destroy', as: :logout_path
  post '/sessions', to: 'sessions#create', as: :login_path
  get '/success', to: 'users#success', as: :success_path

  post '/incoming', to: 'calls#incoming', as: :calls_path
  post '/select_conference', to: 'calls#select_conference'
  post '/authenticate/:id', to: 'calls#authenticate'
  post '/incoming_sms', to: 'calls#incoming_sms'
  post '/callback', to: 'calls#callback'
  get '/expired', to: 'sessions#account_expired', as: :account_expired
  get '/forgot_password', to: 'sessions#forgot_password', as: :forgot_password_path
  post '/generate_token', to: 'sessions#generate_token', as: :generate_token_path
  get '/reset_password', to: 'sessions#reset_password_form', as: :reset_password_form_path
  post '/reset_password', to: 'sessions#reset_password', as: :reset_password_path
  post '/client_join', to: 'calls#client_join'
end

app/models/conference.rb
class Conference < ApplicationRecord
	belongs_to :user
	validates_presence_of :user
	validates :start_time, presence: true
	validates :end_time, presence: true
	validate :are_times_logical
	validates :admin_pin, presence: true
	validates :name, length: { in: 3..20,
														 message: "is too long or too short"}
	has_many :conference_contacts
	has_many :contacts, through: :conference_contacts
	validate :exceeds_max_per_user?
	validate :exceeds_max_participants?

	def exceeds_max_per_user?
		errors.add(:base, "exceeds maximum number of conferences allowed in demo mode") if self.user.conferences.count >= 5
	end

	def exceeds_max_participants?
		max_participants = 250
		if ENV["MAX_PARTICIPANTS"]
			max_participants = ENV["MAX_PARTICIPANTS"].to_i if (2..250).include?(ENV["MAX_PARTICIPANTS"].to_i)
		end
		errors.add(:base, "exceeds maximum participants") if self.conference_contacts.count + 1 > max_participants
	end

	def pin
		BCrypt::Password.new(self.admin_pin)
	end

	def authenticate(entered_pin)
		self.pin == entered_pin
	end

	def set_pin
		proposed_pin = rand.to_s[2..7]
		if self.persisted?
			if self.conference_contacts.any? {|c| c.authenticate(proposed_pin) }
				until self.conference_contacts.none? {|c| c.authenticate(proposed_pin) }
					proposed_pin = rand.to_s[2..7]
				end
			end
		end
		self.admin_pin = BCrypt::Password.create(proposed_pin)
		self.save
		proposed_pin
	end

	def are_times_logical
		if end_time - start_time < 300 || end_time - start_time > 900
			errors.add(:end_time, "must be at least 5 minutes and no more than 15 minutes after start time")
		end
		if start_time < Time.now + 600
			errors.add(:start_time, "must be at least 10 minutes from now")
		end
		if self.user.expiration
			if end_time > self.user.expiration
				errors.add(:end_time, "must be before user account expires")
			end
		end
	end

	def inform_admin(pin)
    greeting = "Hi #{self.user.name}, you have successfully created the conference #{self.name}. Please call this number on #{pretty_time(self.start_time)}."
		pin_msg = "Conference code: #{self.access_code}\nAdmin PIN: #{pin}"
		client = Twilio::REST::Client.new ENV["TWILIO_SID"], ENV["TWILIO_AUTH_TOKEN"]
		client.messages.create(
			from: ENV["TWILIO_NUMBER"],
			to: "+1#{self.user.phone}",
			body: "#{greeting}\n\n#{pin_msg}"
			)
	end

	def remove_access_code
		self.update_attribute(:access_code, nil)
	end

	def pretty_time(time_obj)
		time_obj.in_time_zone(self.user.time_zone).strftime('%b %d %Y at %l:%M %p %Z')
	end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
	before_action :redirect_expired_account
	around_action :user_time_zone, only: [:edit, :show, :index, :create, :update]

	def new
		if helpers.current_user.conference_count >= 5
			@errors = ["Maximum conferences exceeded for trial account."]
			@conferences = []
			@user = helpers.current_user
			render :index
		end
		@conference = Conference.new unless @conference
	end

	def create
		redirect_to :root unless helpers.logged_in?
		if helpers.current_user.conference_count >= 5
			@errors = ["Maximum conferences exceeded for trial account."]
			@conferences = []
			@user = helpers.current_user
			render :index
		end	
		@conference = Conference.new(conference_params)
		@conference.user = helpers.current_user
		@conference.access_code = rand.to_s[2..7]
		admin_pin = @conference.set_pin
		if @conference.valid?
			@conference.conference_contacts << params['conference']['contacts'].reject {|id| id.length == 0 || Contact.find(id).user != helpers.current_user }.map { |id| ConferenceContact.new(contact_id: id, conference: @conference).set_pin }
			@conference.inform_admin(admin_pin)
		end
		if @conference.save
			@conference.user.increment!(:conference_count)
			redirect_to @conference
		else
			@errors = @conference.errors.full_messages
			render :new
		end

	end

	def edit
		redirect_to :root unless helpers.logged_in?
		@conference = Conference.find_by_id(params[:id])
		redirect_to conferences_path unless @conference
		redirect_to conferences_path unless @conference.user == helpers.current_user
		redirect_to @conference if Time.now > @conference.start_time
		# render :edit
	end

	def update
		redirect_to :root unless helpers.logged_in?
		@conference = Conference.find_by_id(params[:id])
		redirect_to conferences_path unless @conference
		redirect_to conferences_path unless @conference.user == helpers.current_user
		if Time.now > @conference.start_time
			redirect_to @conference
		else
			@conference.assign_attributes(update_conference_params)
			if @conference.valid?
				existing_contact_ids = @conference.conference_contacts.map { |contact| contact.contact.id }
				updated_contact_ids = params['conference']['contacts'].reject {|id| id.length == 0 || Contact.find(id).user != helpers.current_user }.map(&:to_i)
				remaining_contact_ids = existing_contact_ids & updated_contact_ids
				uninvited_contact_ids = existing_contact_ids - remaining_contact_ids
				uninvited_contact_ids.map { |id| ConferenceContact.where("contact_id = ? and conference_id = ?", id, @conference.id) }.flatten.each { |c| c.inform_canceled }
				remaining_contact_ids.map { |id| ConferenceContact.where("contact_id = ? and conference_id = ?", id, @conference.id) }.flatten.each { |c| c.inform_updated_time }
				new_contact_ids = updated_contact_ids - remaining_contact_ids
				@conference.conference_contacts << new_contact_ids.map {|id| ConferenceContact.new(contact_id: id, conference: @conference).set_pin }
			end
			if @conference.save
				redirect_to @conference
			else
				@errors = @conference.errors.full_messages
				render :edit
			end
		end
	end

	def destroy
		redirect_to :root unless helpers.logged_in?
		@conference = Conference.find_by_id(params[:id])
		redirect_to conferences_path unless @conference
		redirect_to conferences_path unless @conference.user == helpers.current_user
		if Time.now > @conference.start_time
			redirect_to @conference
		else
			@conference.conference_contacts.each { |contact| contact.inform_canceled }
			@conference.destroy
			redirect_to conferences_path
		end
	end

	def index
		redirect_to :root unless helpers.logged_in?
		@user = helpers.current_user
		@conferences = Conference.where("user_id = ? and end_time > ?", @user.id, Time.now).order(:start_time)
		render :index
	end

	def show
		redirect_to :root unless helpers.logged_in?
		@conference = Conference.find_by_id(params[:id])
		redirect_to conferences_path unless @conference
		redirect_to :root unless helpers.current_user == @conference.user
		if Time.now > @conference.start_time - 300 && Time.now < @conference.end_time
	  	capability = Twilio::JWT::ClientCapability.new ENV['TWILIO_SID'], ENV['TWILIO_AUTH_TOKEN']
	  	capability.add_scope(Twilio::JWT::ClientCapability::OutgoingClientScope.new(ENV['TWILIO_TWIML_APP_SID'], nil, {'Conference' => @conference.access_code}))
	  	@token = capability.to_jwt
	  end
	end

	private
	def conference_params
		params.require(:conference).permit :name, :start_time, :end_time, :contacts, :moderated
	end

	def update_conference_params
		params.require(:conference).permit :start_time, :end_time, :contacts, :moderated
	end

	def user_time_zone
	  Time.use_zone(helpers.current_user.time_zone) { yield } if helpers.logged_in?
	end

	def redirect_expired_account
		if helpers.logged_in?
			if Time.now > (helpers.current_user.expiration || Time.now + 604800)
				session.delete(:user_id)
				redirect_to account_expired_url
			end
		end
	end

end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/edit.html.erb
<h1>Edit a conference</h1>
<fieldset>
	<%= form_for(@conference, url: conference_path(@conference), method: 'patch', class: 'form-horizontal') do |f| %>
		<div class="form-group">
			<%= f.label(:name, "Conference name", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.text_field(:name, class: "form-control", disabled: true) %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:start_time, "Start time", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.datetime_local_field(:start_time, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:end_time, "End time", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.datetime_local_field(:end_time, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:contacts, "Participants", class: "col-lg-2 control-label") %>
			<input name="conference[contacts][]" type="hidden" value="" />
			<div class="col-lg-10">
				<select multiple="multiple" size="5" name="conference[contacts][]" id="conference_contacts" class="form-control">
				<% @conference.user.contacts.each do |contact| %>
					<option value="<%= contact.id %>" <%= "selected='selected'" if ConferenceContact.where("contact_id = ? AND conference_id = ?", contact.id, @conference.id).any? %>><%= contact.name %></option>
				<% end %>
				</select>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:moderated, "Moderated conference?", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<div class="radio">
					<label>
						<% if @conference.moderated %>
							<%= f.radio_button(:moderated, "false") %>no
						<% else %>
							<%= f.radio_button(:moderated, "false", checked: true) %>no
						<% end %>
					</label>
				</div>
				<div class="radio">
					<label>
						<% if @conference.moderated %>
							<%= f.radio_button(:moderated, "true", checked: true) %>yes
						<% else %>
							<%= f.radio_button(:moderated, "true") %>yes
						<% end %>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<%= f.submit("Update conference", class: "btn btn-primary") %>
			</div>
		</div>
	<% end %>
</fieldset>

app/views/conferences/index.html.erb
<h1>Your Upcoming Conferences</h1>
<div>
	<%= link_to("New Conference", new_conference_path, class: "btn btn-success") if current_user.conference_count < 5 %>
</div>
<% if @conferences.any? %>
	<% @conferences.each do |conference| %>
		<div class="panel panel-info">
  		<div class="panel-heading">
    		<h3 class="panel-title"><%= link_to(conference.name, conference) %></h3>
  		</div>
  		<div class="panel-body">
				<p><%= conference.start_time.strftime('%b %d, %Y from %l:%M %p') %> to <%= conference.end_time.strftime('%l:%M %p %Z') %></p>
				<p><%= conference.conference_contacts.count %> participants</p>
				<span><%= link_to("Delete", conference, method: "delete", class: "btn btn-danger btn-sm") %> <%= link_to("Edit", edit_conference_path(conference), class: "btn btn-info btn-sm") %></span>
  		</div>
		</div>
	<% end %>
<% else %>
<div class="alert alert-dismissible alert-info">
  You have no upcoming conferences!
</div>
<% end %>

app/views/conferences/new.html.erb
<h1>Create a conference</h1>
<fieldset>
	<%= form_for(@conference, url: conferences_path, method: 'post', class: 'form-horizontal') do |f| %>
		<div class="form-group">
			<%= f.label(:name, "Conference name", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.text_field(:name, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:start_time, "Start time", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.datetime_local_field(:start_time, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:end_time, "End time", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.datetime_local_field(:end_time, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
		<%= f.label(:contacts, "Participants", class: "col-lg-2 control-label") %>
		<div class="col-lg-10">
			<%= f.collection_select(:contacts, Contact.where('user_id = ?', current_user.id).order(name: :desc), :id, :name, {}, multiple: true, size: 5, class: "form-control") %>
		</div>
		<div class="form-group">
			<%= f.label(:moderated, "Moderated conference?", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<div class="radio">
					<label>
						<%= f.radio_button(:moderated, "false") %>no
					</label>
				</div>
				<div class="radio">
					<label>
						<%= f.radio_button(:moderated, "true", checked: true) %>yes
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<%= f.submit("Create conference", class: "btn btn-primary") %>
			</div>
		</div>
	<% end %>
</fieldset>

app/views/conferences/show.html.erb
<% if @token %>
  <div id="call-controls" style="display: none;">
		<button class="btn btn-success" id="button-call">Join conference</button>
	  <button class="btn btn-danger" id="button-hangup" style="display: none;">Leave conference</button>
	</div>
	<div class="panel panel-success" style="height: 9em;">
	  <div class="panel-heading">
	    <h3 class="panel-title">Fivv Client</h3>
	  </div>
	  <div class="panel-body" id="log" style="overflow-y: scroll; height: 6em;">
	  </div>
	</div>
<% end %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @conference.name %></h3>
  </div>
  <div class="panel-body">
		<p><%= @conference.start_time.strftime('%b %d, %Y from %l:%M %p') %> to <%= @conference.end_time.strftime('%l:%M %p %Z') %></p>
		<% if logged_in? %>
			<% if @conference.conference_contacts.any? %>
				<p>Participants</p>
				<ul>
					<% @conference.conference_contacts.each do |c| %>
						<li><%= c.contact.name %></li>
					<% end %>
				</ul>
			<% else %>
				<div class="alert alert-dismissible alert-warning">
		  		No participants have been added to this conference!
				</div>
			<% end %>
			<% unless Time.now - 300 > @conference.start_time %>
				<span><%= link_to("Delete", @conference, method: "delete", class: "btn btn-danger btn-sm") %> <%= link_to("Edit", edit_conference_path(@conference), class: "btn btn-info btn-sm") %></span>
			<% end %>
		<% end %>
  </div>
</div>
<% if @token %>
  <%= javascript_include_tag "https://media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js" %>
	<%= javascript_tag do %>
  	var token = '<%= @token %>';
	<% end %>
  <%= javascript_include_tag 'client' %>
<% end %>