config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :contacts, :conferences
  
  get '/login', to: 'sessions#new', as: :login_form_path
  delete '/sessions', to: 'sessions#destroy', as: :logout_path
  post '/sessions', to: 'sessions#create', as: :login_path
  get '/success', to: 'users#success', as: :success_path

  post '/incoming', to: 'calls#incoming', as: :calls_path
  post '/select_conference', to: 'calls#select_conference'
  post '/authenticate/:id', to: 'calls#authenticate'
  post '/incoming_sms', to: 'calls#incoming_sms'
  post '/callback', to: 'calls#callback'
  get '/expired', to: 'sessions#account_expired', as: :account_expired
  get '/forgot_password', to: 'sessions#forgot_password', as: :forgot_password_path
  post '/generate_token', to: 'sessions#generate_token', as: :generate_token_path
  get '/reset_password', to: 'sessions#reset_password_form', as: :reset_password_form_path
  post '/reset_password', to: 'sessions#reset_password', as: :reset_password_path
  post '/client_join', to: 'calls#client_join'
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	validates_presence_of :user
	validates :name, length: { in: 2..36,
														 message: "too short or too long" }
	validates :phone, {uniqueness: { scope: :user,
																	 message: "taken by another of your contacts" },
										 format: { with: /\A[^01]\d{9}\z/,
										 					 message: "not a valid phone number"}}
	validates :time_zone, presence: true
	has_many :conference_contacts
	has_many :conferences, through: :conference_contacts

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :redirect_expired_account

	def index
		if helpers.logged_in?
			user = helpers.current_user
			@contacts = Contact.where('user_id = ?', user.id).order(:name)
		else
			redirect_to :root
		end
	end

	def show
		redirect_to :root unless helpers.logged_in?
		@contact = Contact.find_by_id(params[:id])
		redirect_to contacts_path unless @contact
		redirect_to :root unless @contact.user == helpers.current_user
	end

	def new
		redirect_to :root unless helpers.logged_in?
		@contact = Contact.new unless @contact
	end

	def create
		redirect_to :root unless helpers.logged_in?
		@contact = Contact.new(contact_params)
		@contact.phone = @contact.phone.scan(/\d/).join
		@contact.user = helpers.current_user
		if @contact.save
			redirect_to contacts_path
		else
			@errors = @contact.errors.full_messages
			render :new
		end
	end

	def edit
		@contact = Contact.find_by_id(params[:id])
		redirect_to :root if @contact.user != helpers.current_user
	end

	def update
		redirect_to :root unless helpers.logged_in?
		@contact = Contact.find_by_id(params[:id])
		if @contact.user == helpers.current_user
			@contact.assign_attributes(contact_params)
			@contact.phone = @contact.phone.scan(/\d/).join
			if @contact.save
				redirect_to @contact
			else
				@errors = @contact.errors.full_messages
				render :edit
			end
		else
			redirect_to contacts_path
		end
	end

	def destroy
		redirect_to :root unless helpers.logged_in?
		@contact = Contact.find_by_id(params[:id])
		redirect_to contacts_path unless @contact
		@contact.destroy if @contact.user == helpers.current_user
		redirect_to contacts_path
	end


	private
	def contact_params
		params.require(:contact).permit :name, :phone, :time_zone
	end

	def redirect_expired_account
		if helpers.logged_in?
			if Time.now > (helpers.current_user.expiration || Time.now + 604800)
				session.delete(:user_id)
				redirect_to account_expired_url
			end
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Update a contact</h1>
<fieldset>
	<%= form_for(@contact, url: contact_path(@contact), method: 'patch', class: 'form-horizontal') do |f| %>
		<div class="form-group">
			<%= f.label(:name, "Name", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.text_field(:name, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:phone, "Phone", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.telephone_field(:phone, class: "form-control", maxlength: 10) %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:time_zone, "Time zone", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {default: "Eastern Time (US & Canada)"}, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<%= f.submit("Update contact", class: "btn btn-primary") %>
			</div>
		</div>
	<% end %>
</fieldset>
<%= link_to("Return to contacts", contacts_path, class: "btn btn-success") %>
<%= javascript_include_tag 'jquery.maskedinput' %>
<%= javascript_tag do %>
	jQuery(function($){
   $("#contact_phone").mask("999-999-9999");
	});
<% end %>

app/views/contacts/index.html.erb
<h1>Your Contacts</h1>
<div>
	<%= link_to("New Contact", new_contact_path, class: "btn btn-success") %>
</div>
<% if @contacts.any? %>
	<% @contacts.each do |contact| %>
		<div class="panel panel-info">
  		<div class="panel-heading">
    		<h3 class="panel-title"><%= link_to(contact.name, contact) %></h3>
  		</div>
  		<div class="panel-body">
				<p>Number: <%= number_to_phone(contact.phone) %></p>
				<p>Time zone: <%= contact.time_zone %></p>
				<span><%= link_to("Delete", contact, method: "delete", class: "btn btn-danger btn-sm") %> <%= link_to("Edit", edit_contact_path(contact), class: "btn btn-info btn-sm") %></span>
  		</div>
		</div>
	<% end %>
<% else %>
<div class="alert alert-dismissible alert-info">
  You don't have any contacts yet!
</div>
<% end %>

app/views/contacts/new.html.erb
<h1>Create a contact</h1>
<fieldset>
	<%= form_for(@contact, url: contacts_path, method: 'post', class: 'form-horizontal') do |f| %>
		<div class="form-group">
			<%= f.label(:name, "Name", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.text_field(:name, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:phone, "Phone", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.telephone_field(:phone, class: "form-control", maxlength: 10) %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label(:time_zone, "Time zone", class: "col-lg-2 control-label") %>
			<div class="col-lg-10">
				<%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {default: "Eastern Time (US & Canada)"}, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<%= f.submit("Create Contact", class: "btn btn-primary") %>
			</div>
		</div>
	<% end %>
</fieldset>
<%= link_to("Return to contacts", contacts_path, class: "btn btn-success") %>
<%= javascript_include_tag 'jquery.maskedinput' %>
<%= javascript_tag do %>
	jQuery(function($){
   $("#contact_phone").mask("999-999-9999");
	});
<% end %>

app/views/contacts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @contact.name %></h3>
  </div>
  <div class="panel-body">
		<p>Number: <%= number_to_phone(@contact.phone) %></p>
		<p>Time zone: <%= @contact.time_zone %></p>
		<span><%= link_to("Delete", @contact, method: "delete", class: "btn btn-danger btn-sm") %> <%= link_to("Edit", edit_contact_path(@contact), class: "btn btn-info btn-sm") %></span>
  </div>
</div>
<%= link_to("Return to contacts", contacts_path, class: "btn btn-success") %>