config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :contacts, :conferences
  
  get '/login', to: 'sessions#new', as: :login_form_path
  delete '/sessions', to: 'sessions#destroy', as: :logout_path
  post '/sessions', to: 'sessions#create', as: :login_path
  get '/success', to: 'users#success', as: :success_path

  post '/incoming', to: 'calls#incoming', as: :calls_path
  post '/select_conference', to: 'calls#select_conference'
  post '/authenticate/:id', to: 'calls#authenticate'
  post '/incoming_sms', to: 'calls#incoming_sms'
  post '/callback', to: 'calls#callback'
  get '/expired', to: 'sessions#account_expired', as: :account_expired
  get '/forgot_password', to: 'sessions#forgot_password', as: :forgot_password_path
  post '/generate_token', to: 'sessions#generate_token', as: :generate_token_path
  get '/reset_password', to: 'sessions#reset_password_form', as: :reset_password_form_path
  post '/reset_password', to: 'sessions#reset_password', as: :reset_password_path
  post '/client_join', to: 'calls#client_join'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fivv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
      <% if logged_in? %>
        <div class="navbar-header">
          <%= link_to("Fivv", current_user, class: "navbar-brand") %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to("Contacts", contacts_path) %></li>
            <li><%= link_to("Conferences", conferences_path) %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to("Settings", edit_user_path(current_user)) %></li>
            <li><%= link_to("Log out", logout_path_url, method: "delete") %></li>
          </ul>
        </div>
      <% else %>
        <div class="navbar-header">
          <%= link_to("Fivv", root_path, class: "navbar-brand") %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to("Register", new_user_path) %></li>
            <li><%= link_to("Login", login_form_path_url) %></li>
          </ul>
        </div>
      <% end %>
      </div>
    </nav>
    <main>
      <% if @errors %>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Errors</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @errors.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <p class="text-muted">Created by <a href="https://samhopkins.tech/">Sam Hopkins</a></p>
  </body>
</html>